//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.ProductInSales = new HashSet<ProductInSale>();
        }
    
        public long SaleID { get; set; }
        public string IDNumber { get; set; }
        public int StaffID { get; set; }
        public byte BOfficeID { get; set; }
        public System.DateTime STARTOF { get; set; }
        public System.DateTime EOF { get; set; }
    
        public virtual BranchOffice BranchOffice { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInSale> ProductInSales { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
