//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Log
    {
        public long LogID { get; set; }
        public int StaffID { get; set; }
        public int Register { get; set; }
        public System.DateTime ShiftStart { get; set; }
        public System.DateTime ShiftEnd { get; set; }
        public int MoneyOnShiftStart { get; set; }
        public int MoneyOnShiftEnd { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
