CREATE TABLE Product
(
    EAN CHAR(13) UNIQUE NOT NULL, 
    Name NVARCHAR(100) NOT NULL, 
    Price INT NOT NULL, 
    Quantity INT NOT NULL, 
    DailyAverageSales INT NOT NULL, 
    DaysBtwnShipment INT NOT NULL
);
CREATE TABLE Customer
(
    IDNumber CHAR(9) UNIQUE NOT NULL , 
	Name NVARCHAR(30) NOT NULL, 
	LastName1 NVARCHAR(30) NOT NULL, 
	LastName2 NVARCHAR(30) NOT NULL
);
CREATE TABLE BranchOffice
(
	OfficeID TINYINT UNIQUE NOT NULL, 
	Name NVARCHAR(30) NOT NULL, 
	PhoneNumber NVARCHAR(12) NOT NULL, 
	Location NVARCHAR(50) NOT NULL
);
CREATE TABLE Staff
(
	StaffID INT UNIQUE IDENTITY(1001, 1) NOT NULL, 
	BOfficeID TINYINT NOT NULL, 
	Name NVARCHAR(30) NOT NULL, 
	LastName1 NVARCHAR(30) NOT NULL, 
	LastName2 NVARCHAR(30) NOT NULL
);
CREATE TABLE Sale
(
    SaleID BIGINT IDENTITY(1, 1) UNIQUE NOT NULL, 
	IDNumber CHAR(9) NOT NULL,  --client info
	StaffID INT NOT NULL,  --staff info
	BOfficeID TINYINT NOT NULL, 
	STARTOF DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	EOF DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ProductInSale
(
	EAN CHAR(13) NOT NULL, 
	SaleID BIGINT NOT NULL, 
	Quantity INT NOT NULL
);
CREATE TABLE Staff_Log
(
	LogID BIGINT IDENTITY(1, 1) UNIQUE NOT NULL, 
	StaffID INT NOT NULL, 
	Register INT NOT NULL, 
	ShiftStart DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	ShiftEnd DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	MoneyOnShiftStart INT NOT NULL, 
	MoneyOnShiftEnd INT NOT NULL DEFAULT 0
);
CREATE TABLE Supplier
(
	SupplerID TINYINT IDENTITY(1, 1) UNIQUE NOT NULL, 
	Name NVARCHAR(30) NOT NULL, 
	PhoneNumber NVARCHAR(12) NOT NULL
);